import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../src/game.js';
import {SaveManager} from '../src/save.js';
import {BUILDINGS,UNITS,TILE,waveComposition} from '../src/data.js';
const tick=(g,s)=>{for(let i=0;i<s*10;i++)g.update(.1);};
function flat(design=0){const g=new Game(12,'normal',null,{keepDesign:design});for(const t of g.world.tiles)Object.assign(t,{type:'grass',resource:null,amount:0});g.keep.level=3;g.timer=10000;g.hasActed=true;g.revision++;for(const r in g.resources)g.resources[r]=5000;return g;}

test('walls connect to tower edges, including a multi-tile ballista platform',()=>{const g=flat(),a=g.addBuilding('wall',35,30,true),b=g.addBuilding('tower',36,30,true),c=g.addBuilding('ballista',37,30,true),d=g.addBuilding('wall',39,31,true);assert.equal(g.connectionMask(a)&2,2);assert.equal(g.connectionMask(c)&2,2);assert.deepEqual(g.wallPath(a.id,d.id),[b.id,c.id,d.id]);});
test('archers traverse connected walls without dismounting, save their order, and receive cover',()=>{const g=flat();g.units=[];const walls=[35,36,37,38].map(x=>g.addBuilding(x===37?'tower':'wall',x,30,true)),u=g.addUnit('archer',35.5*TILE,31.5*TILE);g.selected=[u.id];g.garrison(walls[0]);tick(g,3);assert.equal(u.garrison,walls[0].id);g.command(walls[3]);assert.equal(u.mountOrder,walls[3].id);tick(g,.3);assert.ok(u.garrison);const restored=Game.restore(JSON.parse(JSON.stringify(g.serialize()))),archer=restored.units[0];tick(restored,4);assert.equal(archer.garrison,walls[3].id);const e=restored.spawnEnemy('bow',archer.x+100,archer.y),hp=archer.hp;restored.damageEntity(e,archer,30);assert.ok(Math.abs(hp-archer.hp-13.5)<.001);});
test('a broken wall connection stops a reposition order without crossing the gap',()=>{const g=flat();g.units=[];const a=g.addBuilding('wall',35,30,true),b=g.addBuilding('wall',36,30,true),c=g.addBuilding('wall',37,30,true),u=g.addUnit('archer',a.x,a.y);u.garrison=a.id;g.selected=[u.id];g.garrison(c);b.hp=0;g.clean();g.updateGarrison(u,.1);assert.equal(u.garrison,a.id);assert.equal(u.mountOrder,null);assert.equal(u.x,a.x);});
test('roads are chosen only when their travel time beats the direct route',()=>{const g=flat(),from={x:20.5*TILE,y:20.5*TILE},to={x:40.5*TILE,y:20.5*TILE};for(let x=20;x<=40;x++)g.addBuilding('road',x,21,true);const path=g.world.path(from,to,g.buildings,{revision:g.revision});assert.ok(path.some(p=>Math.floor(p.y/TILE)===21));g.buildings=g.buildings.filter(b=>b.type!=='road');for(let x=20;x<=40;x++)g.addBuilding('road',x,30,true);const direct=g.world.path(from,to,g.buildings,{revision:g.revision});assert.ok(direct.every(p=>Math.floor(p.y/TILE)===20));});
test('unfinished roads do not provide shortcut routing until completed',()=>{const g=flat();for(let x=20;x<=40;x++)g.addBuilding('road',x,21);const p=g.world.path({x:20.5*TILE,y:20.5*TILE},{x:40.5*TILE,y:20.5*TILE},g.buildings);assert.ok(p.every(p=>Math.floor(p.y/TILE)===20));});
test('all selected units get reachable formation goals beside blocked tiles and keep selection',()=>{const g=flat();g.units=[];for(let i=0;i<24;i++)g.addUnit(i%2?'archer':'militia',(20+i%6*.3)*TILE,(20+Math.floor(i/6)*.3)*TILE);g.addBuilding('house',35,30,true);g.world.tile(36,32).type='mountain';g.revision++;const ids=g.units.map(u=>u.id);g.selected=ids;g.command({x:35.7*TILE,y:30.5*TILE});assert.deepEqual(g.selected,ids);assert.ok(g.units.every(u=>u.target));tick(g,25);assert.ok(g.units.every(u=>u.x>32*TILE));});
test('canceling an unfinished saved site restores exact covered resources, but demolition does not',()=>{const g=flat(),t=g.world.tile(35,30);Object.assign(t,{resource:'wood',amount:137});const b=g.place('house',35,30);b.progress=2;const restored=Game.restore(JSON.parse(JSON.stringify(g.serialize()))),site=restored.buildings.find(v=>v.id===b.id);restored.demolish(site);assert.equal(restored.world.tile(35,30).resource,'wood');assert.equal(restored.world.tile(35,30).amount,137);const built=g.place('house',39,30);Object.assign(g.world.tile(39,30),{resource:null,amount:0});tick(g,40);assert.ok(b.complete&&built.complete);g.demolish(b);assert.equal(t.resource,null);});
test('Keep perks affect combat, storage and real gold collection without changing saved maps',()=>{const coastal=flat(0),highland=flat(1),royal=flat(2),demon=flat(3);assert.equal(coastal.towerDamage(coastal.keep),20*3*1.25);assert.equal(coastal.towerRange(coastal.keep),312);assert.equal(highland.storage,2200);assert.equal(demon.towerRange(demon.keep),312);const u=demon.addUnit('militia',1000,1000);assert.equal(demon.attackDamage(u),14*1.15);royal.resources.gold=0;royal.units=royal.units.slice(0,1);Object.assign(royal.world.tile(35,30),{resource:'gold',amount:8});const mine=royal.addBuilding('goldmine',35,27,true);royal.assign(royal.units[0],mine,'gather');tick(royal,70);assert.equal(royal.resources.gold,10);});
test('Demon Castle unlock is awarded after Nightmare victory and survives replacing the kingdom',()=>{const map=new Map(),storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)},saves=new SaveManager(storage),g=flat();assert.equal(saves.demonUnlocked(),false);g.difficulty='nightmare';g.wave=60;g.active=true;g.update(.1);assert.equal(g.victory,true);saves.save(g);assert.equal(new SaveManager(storage).demonUnlocked(),true);saves.save(new Game(5));assert.equal(new SaveManager(storage).demonUnlocked(),true);});
test('infantry and mounted knights use different trainers; cavalry checks both prerequisites',()=>{const g=flat();g.addBuilding('house',38,34,true);g.addBuilding('stable',40,30,true);assert.match(g.recruitmentReason('mountedknight'),/Barracks/);assert.match(g.recruitmentReason('mountedarcher'),/Archery Range/);const barracks=g.addBuilding('barracks',34,27,true);g.addBuilding('range',39,27,true);assert.ok(g.recruit('mountedknight'));assert.ok(g.recruit('mountedarcher'));assert.ok(g.recruit('knight'));assert.equal(barracks.training[0].type,'knight');const stable=g.buildings.find(b=>b.type==='stable');assert.deepEqual(stable.training.map(q=>q.type),['mountedknight','mountedarcher']);tick(g,65);assert.ok(g.units.some(u=>u.type==='mountedarcher'));assert.ok(g.units.some(u=>u.type==='knight'));});
test('old saved knights and training orders migrate to mounted knights once',()=>{const g=flat();g.addUnit('knight',1000,1000);const b=g.addBuilding('stable',40,30,true);b.training=[{id:999,type:'knight',progress:2,duration:32}];const data=g.serialize();delete data.rosterVersion;const restored=Game.restore(JSON.parse(JSON.stringify(data)));assert.equal(restored.units.at(-1).type,'mountedknight');assert.equal(restored.buildings.at(-1).training[0].cost.food,70);restored.addUnit('knight',1000,1000);assert.equal(Game.restore(JSON.parse(JSON.stringify(restored.serialize()))).units.at(-1).type,'knight');});
test('Blacksmith research requires its tier, pauses if that tier is lost, and masonry improves existing and future buildings',()=>{const g=flat(),smith=g.addBuilding('smith',36,27,true);g.researched=['forestry'];assert.match(g.researchReason('woodspeed'),/level 2/);smith.level=2;assert.ok(g.research('woodspeed'));smith.level=1;g.updateProgression(10);assert.equal(g.researchTask.progress,0);smith.level=3;g.updateProgression(46);assert.equal(g.researchBonus('woodspeed'),.3);g.researched.push('logistics');const low=g.addBuilding('house',40,27,true);assert.ok(g.research('masonry'));g.updateProgression(101);assert.equal(low.level,2);assert.equal(g.keep.level,3);const future=g.place('house',42,27);tick(g,40);assert.equal(future.level,2);});
test('steel axes reduce actual wood harvesting time',()=>{const g=flat();const u=g.units[0],t=g.world.tile(35,30),b=g.addBuilding('lumber',35,27,true);Object.assign(t,{resource:'wood',amount:300});u.x=35.5*TILE;u.y=30.5*TILE;g.assign(u,b,'gather');g.worker(u,1.1);assert.equal(u.job.carry,0);g.researched=['woodspeed'];g.worker(u,.01);assert.equal(u.job.carry,4);});
test('only one Temple is permitted and queued Clerics count against its level cap',()=>{const g=flat();g.addBuilding('house',38,34,true);const t=g.place('temple',36,27);assert.ok(t);assert.equal(g.place('temple',42,27),false);tick(g,40);assert.ok(g.recruit('cleric'));assert.ok(g.recruit('cleric'));assert.match(g.recruitmentReason('cleric'),/cap/);t.level=2;assert.ok(g.recruit('cleric'));assert.equal(g.clericCap,4);});
test('Clerics heal three wounded allies, Mass Heal heals all, and medicine scales healing',()=>{const g=flat();g.units=[];const c=g.addUnit('cleric',1000,1000),allies=Array.from({length:5},(_,i)=>g.addUnit('militia',1010+i*10,1000));for(const u of allies)u.hp=20;g.updateSupport(.1);assert.equal(allies.filter(u=>u.hp>20).length,3);g.researched=['medicine1','medicine2','medicine3','massheal'];c.healClock=1;c.massHealClock=0;const before=allies.map(u=>u.hp);g.updateSupport(.1);assert.ok(allies.every((u,i)=>Math.abs(u.hp-before[i]-26)<.001));});
test('Cleric buffs do not stack and disappear out of range; Temple provides passive healing',()=>{const g=flat();g.units=[];const u=g.addUnit('militia',1000,1000),a=g.addUnit('cleric',1020,1000),b=g.addUnit('cleric',1030,1000);g.researched=['blessing1','blessing2','blessing3'];g.updateSupport(.1);assert.ok(Math.abs(g.attackDamage(u)-14*1.15)<.001);assert.equal(u.clericArmor,3);u.x=1400;g.updateSupport(.1);assert.equal(u.clericBuff,0);g.units=[u];const t=g.addBuilding('temple',35,25,true);u.x=t.x;u.y=t.y;u.hp=40;g.updateSupport(.1);assert.equal(u.hp,43);});
test('Temple research uses Temple levels independently from the Blacksmith',()=>{const g=flat();g.addBuilding('smith',35,27,true).level=5;assert.match(g.researchReason('medicine1'),/Temple/);const t=g.addBuilding('temple',40,27,true);assert.ok(g.research('medicine1'));g.updateProgression(46);assert.match(g.researchReason('medicine2'),/Temple level 2/);t.level=2;assert.ok(g.research('medicine2'));});
test('additional dragon riders arrive airborne in later waves and reject melee',()=>{assert.ok(waveComposition(16).includes('dragonrider'));assert.ok(waveComposition(32).includes('elderdragonrider'));const g=flat(),u=g.addUnit('knight',1000,1000);for(const type of ['dragonrider','elderdragonrider']){const e=g.spawnEnemy(type,1010,1000);assert.equal(g.canDamage(u,e),false);assert.equal(g.canDamage(g.keep,e),true);}});
test('older Nightmare victory saves retain the castle reward when a new run overwrites them',()=>{const map=new Map(),storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)},g=flat();g.difficulty='nightmare';g.victory=true;const old=g.serialize();delete old.nightmareComplete;map.set('tidehold.save.v1',JSON.stringify(old));const saves=new SaveManager(storage);assert.equal(saves.demonUnlocked(),true);saves.save(new Game(2));assert.equal(new SaveManager(storage).demonUnlocked(),true);});

test('Easy ends after wave 40 clears, preserves active foes, and supports endless continuation',()=>{const g=flat();g.difficulty='easy';assert.equal(g.campaignLength(),40);g.wave=39;g.active=true;g.update(.1);assert.equal(g.over,false);g.wave=40;g.active=true;const e=g.spawnEnemy('warlord',1000,1000);g.update(.1);assert.equal(g.over,false);g.enemies=[];g.ships=[];g.hazards=[];g.update(.1);assert.equal(g.victory,true);const saved=Game.restore(JSON.parse(JSON.stringify(g.serialize())));assert.equal(saved.campaignLength(),40);assert.equal(saved.victory,true);g.endless=true;g.over=false;g.victory=false;g.startWave();assert.equal(g.wave,41);g.enemies=[];g.ships=[];g.active=true;g.update(.1);assert.equal(g.over,false);for(const [difficulty,length] of [['normal',50],['hard',50],['nightmare',60]]){g.difficulty=difficulty;assert.equal(g.campaignLength(),length);}});
