import test from 'node:test';
import assert from 'node:assert/strict';
import {GamePlatform} from '../src/platform.js';
import {SaveManager} from '../src/save.js';
import {encodeSave,decodeSave} from '../src/save-codec.js';
import {Game} from '../src/game.js';
import {AudioManager} from '../src/audio.js';
const memory=()=>{const map=new Map();return {map,getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)};};
function fake(){const calls=[],data=memory();return {calls,sdk:{environment:'crazygames',init:async()=>calls.push('init'),data,game:{settings:{muteAudio:true},addSettingsChangeListener(fn){this.changed=fn;},loadingStart:()=>calls.push('loadingStart'),loadingStop:()=>calls.push('loadingStop'),gameplayStart:()=>calls.push('start'),gameplayStop:()=>calls.push('stop'),happytime:()=>calls.push('happy'),reportGameCompletedPercentage:n=>calls.push(n)}}};}
test('SDK initialization finishes before any Data reads; cloud is authoritative even when empty',async()=>{const {sdk,calls}=fake();let ready; sdk.init=()=>new Promise(r=>ready=r);sdk.data.getItem=()=>{calls.push('read');return null;};const pending=GamePlatform.connect({enabled:true,sdk,localStorage:()=>{throw Error('Local save must not be read');}});assert.deepEqual(calls,[]);ready();const p=await pending;assert.equal(p.storage,sdk.data);assert.deepEqual(calls,['read','loadingStart']);});
test('standard and disabled builds use local storage; SDK failures never silently create a local kingdom',async()=>{const local=memory(),{sdk}=fake();assert.equal((await GamePlatform.connect({localStorage:()=>local})).storage,local);sdk.environment='disabled';assert.equal((await GamePlatform.connect({enabled:true,sdk,localStorage:()=>local})).storage,local);await assert.rejects(GamePlatform.connect({enabled:true,localStorage:()=>local}));sdk.init=async()=>{throw Error('Offline');};await assert.rejects(GamePlatform.connect({enabled:true,sdk,localStorage:()=>local}),/Offline/);sdk.init=()=>new Promise(()=>{});await assert.rejects(GamePlatform.connect({enabled:true,sdk,localStorage:()=>local,timeout:5}),/too long/);});
test('disabled Data module blocks startup without touching local saves',async()=>{const {sdk}=fake();sdk.data.getItem=()=>{throw Error('dataModuleDisabled');};await assert.rejects(GamePlatform.connect({enabled:true,sdk,localStorage:()=>{throw Error('wrong backend');}}),/dataModuleDisabled/);});
test('compact saves preserve legacy tile fields, upgrades, training, jobs, paths, bosses and unlocks exactly',()=>{const g=new Game(77,'nightmare');g.keep.level=3;g.nightmareComplete=true;g.researched=['medicine1'];g.world.tiles[50].legacyField='unchanged';g.world.tiles[51].resource='gold';g.world.tiles[51].amount=123;const temple=g.addBuilding('temple',48,38,true);temple.training=[{id:987,type:'cleric',progress:5,duration:22}];g.spawnEnemy('demonlord',1700,1200).phase='healing';const raw=JSON.parse(JSON.stringify(g.serialize()));assert.deepEqual(decodeSave(encodeSave(raw)),raw);const store=memory(),saves=new SaveManager(store,{compact:true});assert.equal(saves.save(g),true);assert.deepEqual(saves.load().serialize(),raw);assert.equal(new SaveManager(store).demonUnlocked(),true);assert.ok(Buffer.byteLength(store.getItem('tidehold.save.v1'))<600000);});
test('large late-game cloud saves fit the quota with 500 troops and 250 structures',()=>{const g=new Game(42,'nightmare');for(let i=0;i<500;i++)g.addUnit(i%2?'mountedarcher':'cleric',1000+i,1200);for(let i=0;i<250;i++)g.addBuilding('wall',i%90,Math.floor(i/90)+30,true);const s=memory(),saves=new SaveManager(s,{compact:true});assert.ok(saves.save(g));const bytes=Buffer.byteLength(JSON.stringify(Object.fromEntries(s.map)));assert.ok(bytes<970000,`Cloud data: ${bytes}`);assert.equal(saves.load().units.length,505);});
test('old uncompressed saves still load; corrupt tables and quota failures retain the previous save',()=>{const g=new Game(4),s=memory(),save=new SaveManager(s,{compact:true});s.setItem('tidehold.save.v1',JSON.stringify(g.serialize()));assert.equal(save.load().world.seed,4);assert.throws(()=>decodeSave('{"tileTable":{"version":1,"length":1,"groups":[]}}'));const previous=s.getItem('tidehold.save.v1');g.kingdomName='x'.repeat(1000000);assert.equal(save.save(g),false);assert.equal(s.getItem('tidehold.save.v1'),previous);g.kingdomName='Small';s.setItem=()=>{throw Error('SDK quota');};assert.equal(save.save(g),false);assert.equal(s.getItem('tidehold.save.v1'),previous);});
test('gameplay events follow playable state including tutorial, menus and victory, without duplicates or focus-only events',()=>{const {sdk,calls}=fake(),p=new GamePlatform(memory(),sdk),g={paused:false,over:false,victory:false};p.update(g,false);p.update(g,true);p.update(g,true);p.update(g,true,true);assert.deepEqual(calls,['start']);g.paused=true;p.update(g,true);p.update(g,true);g.paused=false;p.update(g,true);g.over=g.victory=true;p.update(g,true);p.update(g,true);assert.deepEqual(calls,['start','stop','start','stop','happy',100]);});
test('portal mute overrides user toggles and volume without overwriting saved preferences',()=>{const {sdk}=fake(),p=new GamePlatform(memory(),sdk),audio=new AudioManager();audio.enabled=true;let gain;audio.context={currentTime:0};audio.master={gain:{setTargetAtTime:n=>gain=n}};audio.buses=Object.fromEntries(Object.keys(audio.levels).map(k=>[k,{gain:{setTargetAtTime:()=>{}}}]));p.attachAudio(audio);assert.equal(gain,0);audio.setEnabled(true);audio.setLevel('music',1);assert.equal(gain,0);sdk.game.changed({muteAudio:false});assert.equal(gain,.65);assert.equal(audio.enabled,true);assert.equal(audio.levels.music,1);});
