import {createRequire} from 'node:module';
import {finalizePreview} from './finalize-crazygames-media.mjs';
import {mkdir,writeFile} from 'node:fs/promises';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/colin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'});
await mkdir('dist/crazygames-submission',{recursive:true});
try{
 const page=await browser.newPage({viewport:{width:1920,height:1080}});await page.goto('http://127.0.0.1:4173/?test');await page.locator('#new-kingdom').click();await page.locator('#new-game').click();await page.evaluate(()=>window.__tidehold.game.paused=true);
 await page.evaluate(()=>{
  window.drawCover=(w,h)=>{
   const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const c=canvas.getContext('2d'),a=window.__tidehold.renderer.art,u=window.__tidehold.renderer.unitArt;
   const sky=c.createLinearGradient(0,0,w,h);sky.addColorStop(0,'#0f242f');sky.addColorStop(.6,'#345a58');sky.addColorStop(1,'#102d36');c.fillStyle=sky;c.fillRect(0,0,w,h);
   c.save();c.translate(w*.5,h*.60);const scale=Math.min(w/850,h/710);c.scale(scale,scale);
   const island=c.createRadialGradient(-60,-80,40,0,0,440);island.addColorStop(0,'#8c9970');island.addColorStop(.65,'#5b775b');island.addColorStop(1,'#2d5048');c.fillStyle=island;c.strokeStyle='#c0b886';c.lineWidth=9;c.beginPath();c.moveTo(-380,-80);c.bezierCurveTo(-410,-260,-200,-270,30,-250);c.bezierCurveTo(280,-250,410,-110,370,100);c.bezierCurveTo(350,220,80,240,-80,220);c.bezierCurveTo(-260,240,-410,150,-380,-80);c.fill();c.stroke();
   c.strokeStyle='#abc9bc44';c.lineWidth=2;for(let i=0;i<5;i++){c.beginPath();c.ellipse(0,20,405+i*20,245+i*12,0,.05,Math.PI-.05);c.stroke();}
   c.strokeStyle='#b4b085';c.lineWidth=23;c.beginPath();c.moveTo(-310,20);c.lineTo(310,20);c.moveTo(0,-220);c.lineTo(0,210);c.stroke();
   const roof=(type,x,y,size,level=2,mask=0)=>{c.save();c.translate(x,y);c.shadowColor='#0d231c88';c.shadowBlur=12;c.shadowOffsetY=12;c.drawImage(a.building(type,level,mask,type==='keep'?2:0),-size/2,-size/2,size,size);c.restore();};
   for(const [x,y]of [[-275,-120],[-220,120],[260,130],[310,-40],[-325,50],[210,-160]]){for(let k=0;k<5;k++){const xx=x+Math.sin(k*2.4)*29,yy=y+Math.cos(k*2.4)*25;a.circle(c,xx+5,yy+9,23,'#203b2d66');a.circle(c,xx,yy,23,'#2a5040');a.circle(c,xx-4,yy-5,17,'#4e7050');a.circle(c,xx-7,yy-8,10,'#728957');}}
   roof('barracks',-175,-100,110);roof('range',175,-100,100);roof('temple',180,100,115);roof('farm',-190,110,115);
   for(let x=-110;x<=110;x+=44){roof('wall',x,-175,58,2,10);roof('wall',x,170,58,2,10);}for(let y=-130;y<150;y+=44){roof('wall',-140,y,58,2,5);roof('wall',140,y,58,2,5);}
   for(const x of [-140,140])for(const y of [-175,170])roof('tower',x,y,87,3);roof('gate',0,170,75);roof('keep',0,-10,242,3);
   for(let i=0;i<8;i++){c.save();c.translate(-90+i*26,110);c.rotate(-Math.PI/2);c.drawImage(u.sprite(i%2?'knight':'archer'),-24,-24,48,48);c.restore();}
   c.save();c.translate(285,-185);c.rotate(-2.5);c.scale(1.7,1.7);u.wings(c,'dragon',0,true);c.drawImage(u.sprite('dragon'),-48,-48,96,96);c.restore();
   c.save();c.translate(-330,165);c.rotate(-.6);c.fillStyle='#ad9567';c.beginPath();c.ellipse(0,0,24,60,0,0,7);c.fill();c.fillStyle='#493a31';c.fillRect(-17,-40,34,80);c.fillStyle='#a04e44';c.fillRect(-21,-20,42,40);c.strokeStyle='#edd5a1';c.lineWidth=4;c.beginPath();c.moveTo(0,-45);c.lineTo(0,45);c.stroke();c.restore();c.restore();
   const shade=c.createLinearGradient(0,0,0,h*.39);shade.addColorStop(0,'#0a182bd9');shade.addColorStop(1,'#0a182b00');c.fillStyle=shade;c.fillRect(0,0,w,h*.39);
   const title=Math.min(w*.13,h*.16);c.textAlign='center';c.font=`bold ${title}px Georgia`;c.shadowColor='#050f1c';c.shadowBlur=18;c.shadowOffsetY=5;c.fillStyle='#f1d697';c.fillText('TIDEHOLD',w/2,h*.18);c.shadowBlur=0;c.shadowOffsetY=0;c.font=`${title*.24}px Georgia`;c.letterSpacing='5px';c.fillStyle='#e0c69e';c.fillText('THE LAST COAST',w/2,h*.18+title*.43);return canvas;
  };
 });
 for(const [name,w,h]of [['landscape',1920,1080],['portrait',800,1200],['square',800,800]]){const base64=await page.evaluate(({w,h})=>{const c=drawCover(w,h);return c.toDataURL('image/png').split(',')[1];},{w,h});await writeFile(`dist/crazygames-submission/cover-${name}.png`,Buffer.from(base64,'base64'));console.log(`Cover ${name}: ${w}x${h}`);}
 if(!process.argv.includes('--covers-only'))for(const [name,w,h]of [['landscape',1920,1080],['portrait',1080,1620]].filter(([name])=>!process.argv.includes('--portrait-only')||name==='portrait')){
  await page.setViewportSize({width:w,height:h});await page.addStyleTag({content:'#hud,#command-dock,#modal,.wave-card,#boss,#map-overview,.camera-controls,#hint,#tray,#inspector,#placement,#tutorial,#toast{display:none!important}#viewport{position:fixed!important;inset:0!important;width:100vw!important;height:100vh!important}*{cursor:none!important}'});
  await page.evaluate(async()=>{const {Game}=await import('/src/game.js'),{TILE}=await import('/src/data.js'),api=window.__tidehold,g=new Game(42,'normal');g.units=[];g.hasActed=true;g.timer=10000;g.wave=24;const sx=g.keep.tx,sy=g.keep.ty;for(const t of g.world.tiles)if(Math.abs(t.x-sx)<12&&Math.abs(t.y-sy)<11)Object.assign(t,{type:'grass',resource:null,amount:0});g.keep.level=3;g.keep.hp=g.keep.maxHp=4680;
   const add=(type,x,y,level=2)=>{const b=g.addBuilding(type,sx+x,sy+y,true);b.level=level;return b;};
   add('temple',4,3);add('barracks',-5,3);add('range',4,-4);add('smith',-5,-4);add('house',-8,5);add('house',6,6);add('farm',2,7);
   for(let x=-6;x<=6;x++)add(x===0?'gate':'wall',x,-6);for(const x of [-6,6]){add('tower',x,-6,3);for(let y=-5;y<=5;y++)add('wall',x,y);}for(let x=-5;x<6;x++)add(x===0?'gate':'wall',x,6);
   for(let i=0;i<14;i++){const b=g.buildings.find(b=>b.type==='wall'&&b.tx===sx-6&&b.ty===sy-5+i%10);const u=g.addUnit('archer',b.x,b.y);u.garrison=b.id;}
   for(let i=0;i<20;i++){const p=g.nearestOpenLand({x:g.keep.x-310+(i%4)*25,y:g.keep.y-90+Math.floor(i/4)*33},80);g.addUnit(i%4?'knight':'mountedknight',p.x,p.y);}g.addUnit('cleric',g.keep.x-190,g.keep.y);g.addUnit('cleric',g.keep.x-180,g.keep.y-80);
   for(let i=0;i<35;i++)g.spawnEnemy(i%5===0?'brute':'raider',g.keep.x-520-(i%5)*20,g.keep.y-150+Math.floor(i/5)*40);g.spawnEnemy('dragonrider',g.keep.x+370,g.keep.y-320);g.active=true;api.setGame(g);api.renderer.camera={x:g.keep.x-(innerWidth>1500?90:140),y:g.keep.y,zoom:innerWidth>1500?1.6:1.1};api.renderer.resize();g.paused=true;});
  const recording=await page.evaluate(async({w,h})=>{const out=document.createElement('canvas');out.width=w;out.height=h;const c=out.getContext('2d'),cover=drawCover(w,h),game=document.getElementById('game');c.drawImage(cover,0,0);const mime=['video/mp4;codecs=avc1.42001f','video/mp4','video/webm;codecs=vp9'].find(t=>MediaRecorder.isTypeSupported(t));if(!mime)throw Error('No video encoder');const stream=out.captureStream(30),rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:6000000}),chunks=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};const done=new Promise(resolve=>rec.onstop=resolve);let running=true;const start=performance.now();function draw(now){if(!running)return;if(now-start<500)c.drawImage(cover,0,0);else{window.__tidehold.game.paused=false;c.drawImage(game,0,0,w,h);}requestAnimationFrame(draw);}rec.start(1000);requestAnimationFrame(draw);await new Promise(r=>setTimeout(r,18000));running=false;rec.stop();await done;window.__tidehold.game.paused=true;stream.getTracks().forEach(t=>t.stop());const bytes=new Uint8Array(await new Blob(chunks,{type:mime}).arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return {base64:btoa(binary),mime,seconds:(performance.now()-start)/1000};},{w,h});const ext=recording.mime.includes('mp4')?'mp4':'webm';if(ext!=='mp4')throw Error('Use a Chrome build with MP4 MediaRecorder support.');await writeFile(`dist/crazygames-submission/preview-${name}.${ext}`,Buffer.from(recording.base64,'base64'));await finalizePreview(name);console.log(`Preview ${name}: ${w}x${h}, ${recording.seconds.toFixed(1)}s, ${ext}`);
 }
}finally{await browser.close();}
