import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {Game} from '../src/game.js';
import {encodeSave} from '../src/save-codec.js';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/colin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'}),sdkURL='https://sdk.crazygames.com/crazygames-sdk-v3.js';
const saved=new Game(91,'normal');saved.kingdomName='Cloud Citadel';saved.nightmareComplete=true;
try{
 for(const [width,height] of [[1440,900],[390,844],[844,390]]){
  const page=await browser.newPage({viewport:{width,height},hasTouch:width<900}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route(sdkURL,route=>route.fulfill({contentType:'text/javascript',body:`window.sdkCalls=[];window.cloudData=${JSON.stringify({'tidehold.save.v1':encodeSave(saved.serialize())})};let ready=false;window.CrazyGames={SDK:{environment:'local',init:async()=>{sdkCalls.push('init');await new Promise(r=>setTimeout(r,100));ready=true;},data:{getItem:k=>{if(!ready)throw Error('Read before init');return cloudData[k]??null;},setItem:(k,v)=>{if(window.failSave)throw Error('SDK quota');sdkCalls.push('save');cloudData[k]=v;}},game:{settings:{muteAudio:true},addSettingsChangeListener:fn=>window.changeMute=fn,loadingStart:()=>sdkCalls.push('loadingStart'),loadingStop:()=>sdkCalls.push('loadingStop'),gameplayStart:()=>sdkCalls.push('start'),gameplayStop:()=>sdkCalls.push('stop'),happytime:()=>sdkCalls.push('happy'),reportGameCompletedPercentage:()=>{}}}};Object.defineProperty(window,'localStorage',{get:()=>{throw Error('Direct localStorage is forbidden in portal build');}});`}));
  await page.goto('http://127.0.0.1:4173/dist/crazygames/index.html?test');await page.locator('#continue').click();await page.waitForFunction(()=>sdkCalls.includes('start'));assert.equal(await page.evaluate(()=>window.__tidehold.game.kingdomName),'Cloud Citadel');assert.equal(await page.evaluate(()=>window.__tidehold.ui.audio.platformMuted),true);
  await page.locator('#menu').click();await page.waitForFunction(()=>sdkCalls.at(-1)==='stop');assert.match(await page.locator('#save').innerText(),/CrazyGames/);await page.locator('#save').click();assert.match(await page.locator('#save').innerText(),/saved/);assert.ok(await page.evaluate(()=>JSON.parse(cloudData['tidehold.save.v1']).tileTable));
  await page.locator('#settings').click();await page.evaluate(()=>{const a=window.__tidehold.ui.audio;a.setEnabled(true);a.setLevel('music',1);});assert.equal(await page.evaluate(()=>window.__tidehold.ui.audio.platformMuted),true);await page.evaluate(()=>changeMute({muteAudio:false}));assert.equal(await page.evaluate(()=>window.__tidehold.ui.audio.platformMuted),false);await page.locator('#settings-back').click();await page.locator('[data-close]').click();await page.waitForFunction(()=>sdkCalls.at(-1)==='start');
  await page.locator('#pause').click();await page.waitForFunction(()=>sdkCalls.at(-1)==='stop');await page.locator('#pause').click();await page.waitForFunction(()=>sdkCalls.at(-1)==='start');
  await page.evaluate(()=>window.failSave=true);await page.locator('#menu').click();await page.locator('#main-menu').click();assert.equal(await page.locator('#new-kingdom').count(),0);assert.match(await page.locator('#modal-body').innerText(),/Saving failed/);await page.evaluate(()=>window.failSave=false);
  await page.setViewportSize({width:height,height:width});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log(`${width}x${height}: cloud preload, compact save, mute, menus, pause, failed-save preservation and orientation passed`);await page.close();
 }
 const failure=await browser.newPage();await failure.route(sdkURL,r=>r.abort());await failure.goto('http://127.0.0.1:4173/dist/crazygames/index.html');assert.ok(await failure.locator('#startup button').isVisible());assert.equal(await failure.locator('#new-kingdom').count(),0);await failure.close();console.log('Missing SDK blocks startup with Retry and does not open an unsynced kingdom.');
 if(process.argv.includes('--live-sdk')){const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4173/dist/crazygames/index.html?test&muteAudio=true');await page.locator('#new-kingdom').click();await page.locator('#new-game').click();await page.locator('#tutorial-skip').click();await page.locator('#menu').click();await page.locator('#save').click();assert.match(await page.locator('#save').innerText(),/saved/);await page.reload();await page.locator('#continue').click();assert.equal(await page.evaluate(()=>window.CrazyGames.SDK.environment),'local');assert.equal(await page.evaluate(()=>window.__tidehold.ui.audio.platformMuted),true);assert.deepEqual(errors,[]);console.log('Official CDN v3 SDK: initialization, Data save/reload and platform mute passed in local mode.');}
}finally{await browser.close();}
