import {createRequire} from 'node:module';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/colin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});await mkdir('artifacts/expansion',{recursive:true});const errors=[];
try{for(const [width,height]of [[1440,900],[768,1024],[390,844],[320,568],[844,390]]){
 const context=await browser.newContext({viewport:{width,height},hasTouch:width<900,isMobile:width<900}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4173/?test');await page.locator('#new-kingdom').click();assert.ok(await page.locator('[data-keep-design="3"]').isDisabled());assert.match(await page.locator('[data-keep-design="1"]').innerText(),/500 storage/);await page.locator('#difficulty').selectOption('easy');assert.match(await page.locator('option[value=easy]').innerText(),/40 waves/);await page.locator('#new-game').click();await page.locator('#tutorial-skip').click();
 await page.evaluate(()=>{const a=window.__tidehold,g=a.game;g.hasActed=true;g.wave=40;g.active=true;g.update(.1);a.ui.update();});assert.match(await page.locator('#wave').innerText(),/40.*40/);await page.locator('#endless').click();assert.equal(await page.evaluate(()=>window.__tidehold.game.endless),true);
 await page.evaluate(()=>{const g=window.__tidehold.game;g.endless=false;g.wave=0;g.active=false;g.timer=10000;});
 await page.evaluate(()=>{const a=window.__tidehold,g=a.game;g.paused=true;for(const t of g.world.tiles)Object.assign(t,{type:'grass',resource:null,amount:0});g.revision++;a.renderer.terrain=null;g.keep.level=3;for(const r in g.resources)g.resources[r]=5000;g.addBuilding('house',28,34,true).level=5;g.addBuilding('barracks',28,27,true);g.addBuilding('stable',28,30,true);g.addBuilding('range',33,27,true);g.addBuilding('smith',36,27,true);const temple=g.addBuilding('temple',36,30,true);g.selected=[temple.id];a.ui.selection();a.ui.update();});
 await page.locator('[data-action=research]').click();assert.ok(await page.locator('[data-research=medicine1]').isVisible());assert.match(await page.locator('[data-research=medicine2]').innerText(),/Temple level 2/);assert.equal(await page.locator('[data-research=forestry]').count(),0);await page.locator('[data-research=medicine1]').click();assert.equal(await page.evaluate(()=>window.__tidehold.game.researchTask.id),'medicine1');
 await page.evaluate(()=>{const a=window.__tidehold,g=a.game;g.updateProgression(46);g.temple.level=2;a.ui.renderPanel(true);});await page.locator('[data-research=massheal]').click();assert.equal(await page.evaluate(()=>window.__tidehold.game.researchTask.id),'massheal');await page.evaluate(()=>{window.__tidehold.ui.toastUntil=0;window.__tidehold.ui.update();document.querySelector('#panel').scrollTop=0;});await page.waitForTimeout(150);await page.screenshot({path:`artifacts/expansion/temple-${width}.png`});await page.locator('#close-tray').click();
 await page.locator('[data-tab=army]').click();await page.locator('[data-army-category=Cavalry]').click();assert.equal(await page.locator('[data-recruit]').count(),2);await page.locator('[data-recruit=mountedarcher]').click();await page.locator('[data-recruit=mountedknight]').click();await page.locator('[data-army-category=Infantry]').click();await page.locator('[data-recruit=knight]').click();await page.locator('[data-army-category=Support]').click();await page.locator('[data-recruit=cleric]').click();assert.equal(await page.evaluate(()=>window.__tidehold.game.buildings.find(b=>b.type==='stable').training.length),2);await page.locator('#close-tray').click();
 await page.evaluate(()=>{const a=window.__tidehold,g=a.game;for(let i=0;i<12;i++)g.addUnit(i%2?'archer':'militia',g.keep.x+(i%4-2)*25,g.keep.y+110+Math.floor(i/4)*20);g.addBuilding('house',g.keep.tx+4,g.keep.ty+4,true);a.renderer.center();});await page.locator('[data-tab=army]').click();await page.locator('[data-action=select-army]').click();const n=await page.evaluate(()=>window.__tidehold.game.selected.length);await page.locator('[data-action=move]').click();const point=await page.evaluate(()=>{const a=window.__tidehold;return a.renderer.worldToScreen(a.game.keep.x+85,a.game.keep.y+85);}),box=await page.locator('#game').boundingBox();if(width<900)await page.touchscreen.tap(box.x+point.x,box.y+point.y);else await page.mouse.click(box.x+point.x,box.y+point.y);assert.equal(await page.evaluate(()=>window.__tidehold.game.selected.length),n);assert.equal(await page.evaluate(()=>window.__tidehold.game.units.filter(u=>u.target).length),n);
 await page.evaluate(()=>{const a=window.__tidehold,g=a.game;g.enemies=[];g.units=g.units.filter(u=>u.type==='worker');const walls=[34,35,36,37].map(x=>g.addBuilding(x===36?'tower':'wall',36,x,true)),u=g.addUnit('archer',walls[0].x,walls[0].y);u.garrison=walls[0].id;g.selected=[u.id];g.command(walls[3]);for(let i=0;i<60;i++)g.updateGarrison(u,.1);a.ui.update();});assert.equal(await page.evaluate(()=>{const g=window.__tidehold.game,u=g.units.at(-1);return u.garrison===g.buildings.at(-1).id;}),true);
 await page.evaluate(()=>{const a=window.__tidehold,g=a.game;g.difficulty='nightmare';g.wave=60;g.active=true;g.enemies=[];g.ships=[];g.portals=[];g.hazards=[];g.paused=false;g.update(.1);a.ui.update();});await page.locator('#again').click();await page.locator('#new-kingdom').click();assert.equal(await page.locator('[data-keep-design="3"]').isDisabled(),false);await page.locator('[data-keep-design="3"]').click();await page.waitForTimeout(250);await page.screenshot({path:`artifacts/expansion/keeps-${width}.png`});await page.locator('#new-game').click();assert.equal(await page.evaluate(()=>window.__tidehold.game.keepDesign),3);
 if(width===1440){const data=await page.evaluate(async()=>{const {ENEMIES,UNITS}=await import('/src/data.js'),a=window.__tidehold,c=document.createElement('canvas');c.width=1200;c.height=700;const ctx=c.getContext('2d');ctx.fillStyle='#243a31';ctx.fillRect(0,0,c.width,c.height);['knight','mountedknight','mountedarcher','cleric','dragonrider','elderdragonrider','dragon','demonlord'].forEach((type,i)=>{const x=i%4*300,y=Math.floor(i/4)*350,d=ENEMIES[type]||UNITS[type];ctx.save();ctx.translate(x+150,y+160);const scale=d.boss||d.scale?Math.min(2,2.8/(d.scale||2.1)):2.8;ctx.scale(scale,scale);a.renderer.unit(ctx,{type,x:0,y:0,hp:1,maxHp:1,facing:-Math.PI/2},!!ENEMIES[type],4);ctx.restore();ctx.fillStyle='#e4d0a2';ctx.font='17px Georgia';ctx.textAlign='center';ctx.fillText(d.name.split(' · ')[0],x+150,y+315);});return c.toDataURL().split(',')[1];});await writeFile('artifacts/expansion/roster.png',Buffer.from(data,'base64'));}
 await page.setViewportSize({width:height,height:width});await page.waitForTimeout(150);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await context.close();console.log(`${width}x${height}: Temple research, cavalry recruitment, full group orders, wall traversal and Nightmare unlock passed`);
}assert.deepEqual(errors,[]);}finally{await browser.close();}
