import {BUILDINGS,UNITS,ENEMIES,TILE,COLS,ROWS,waveComposition,DIFFICULTIES} from './data.js';
import {World,distance,clamp} from './world.js';
import {Construction} from './construction.js';
import {Progression} from './progression.js';
import {Invasions} from './invasions.js';
import {Garrison} from './garrison.js';
import {Nightmare} from './nightmare.js';
import {Combat} from './combat.js';
export class Game {
 constructor(seed=Date.now(),difficulty='normal',savedTiles=null,options={}){
  this.world=new World(seed,savedTiles,{...options,difficulty});this.kingdomName=String(options.name||'Tidehold').trim().slice(0,32)||'Tidehold';this.keepDesign=[0,1,2].includes(options.keepDesign)?options.keepDesign:0;this.difficulty=difficulty;this.resources={wood:250,stone:150,food:150,iron:0,gold:100};for(const k in this.resources)this.resources[k]=Math.round(this.resources[k]*(DIFFICULTIES[difficulty]||DIFFICULTIES.normal).supply);
  this.buildings=[];this.units=[];this.enemies=[];this.ships=[];this.effects=[];this.id=0;this.wave=0;this.timer=(DIFFICULTIES[difficulty]||DIFFICULTIES.normal).peace;this.hasActed=false;this.tutorial=options.tutorial?{step:0,done:false}:null;this.active=false;this.speed=1;this.paused=false;this.over=false;this.victory=false;this.endless=false;this.autoWave=false;this.portals=[];this.hazards=[];this.sealBroken=false;this.sealTime=0;this.demonLordDefeated=false;this.time=0;this.tech=0;this.researched=[];this.researchTask=null;this.selected=[];this.revision=0;this.stats={kills:0,built:0,lost:0,gathered:0};this.notice=()=>{};this.sound=()=>{};this.autosave=()=>{};this.saveClock=0;
  const start=this.world.start;this.addBuilding('keep',start.x-1,start.y-1,true);for(let i=0;i<5;i++)this.addUnit('worker',(start.x-.5)*TILE+i*22,(start.y+3)*TILE);
 }
 noteAction(){this.hasActed=true;}
 get preparationHeld(){return this.wave===0&&(!this.hasActed||this.tutorial&&!this.tutorial.done);}
 get keep(){return this.buildings.find(b=>b.type==='keep');}
 get level(){return this.keep?.level||1;}
 get capacity(){return this.buildings.filter(b=>b.complete&&b.hp>0).reduce((n,b)=>n+(BUILDINGS[b.type].pop||0)*b.level,0);}
 get storage(){return 700+this.buildings.filter(b=>b.type==='warehouse'&&b.complete).length*600;}
 afford(cost){return Object.entries(cost).every(([r,n])=>this.resources[r]>=n);}
 spend(cost){if(!this.afford(cost))return false;for(const [r,n]of Object.entries(cost))this.resources[r]-=n;return true;}
 addBuilding(type,tx,ty,complete=false){const d=BUILDINGS[type],b={id:++this.id,type,tx,ty,x:(tx+d.size/2)*TILE,y:(ty+d.size/2)*TILE,hp:d.hp,maxHp:d.hp,progress:complete?d.time:0,complete,level:1,cooldown:0};this.buildings.push(b);this.revision++;return b;}
 addUnit(type,x,y){const d=UNITS[type],u={id:++this.id,type,x,y,hp:d.hp,maxHp:d.hp,cooldown:0,job:null,path:[],pathRevision:-1,stance:'defend',kills:0};this.units.push(u);return u;}
 assign(u,b,kind){if(!u||u.type!=='worker')return false;const resource=BUILDINGS[b.type].resource;if(kind==='gather'&&resource!=='food'&&!this.world.deposits(resource,b,u,this.buildings,this.revision).length){this.notice('No reachable deposits for this worker. Open a route or choose another mine.');return false;}u.job={building:b.id,kind,stage:'travel',clock:0,carry:0};u.path=[];u.target=null;return true;}
 assignWorker(b){if(!b)return;const d=BUILDINGS[b.type];const workers=this.units.filter(u=>u.job?.building===b.id);if(b.complete&&(!d.workers||workers.length>=d.workers)){this.notice('No available worker slots.');return;}const u=this.units.find(u=>u.type==='worker'&&!u.job);if(!u){this.notice('No idle workers. Train one at the Keep.');return;}if(this.assign(u,b,b.complete?'gather':'build')){this.noteAction();this.notice('Worker assigned.');}}
 removeWorker(b){const u=this.units.find(u=>u.job?.building===b.id);if(u){u.job=null;u.path=[];this.notice('Worker is now idle.');}}
 repair(b){if(!b||!b.complete||b.hp>=b.maxHp)return;const u=this.units.find(u=>u.type==='worker'&&!u.job);if(!u){this.notice('An idle worker is needed for repairs.');return;}const cost={wood:Math.ceil((b.maxHp-b.hp)/35),stone:Math.ceil((b.maxHp-b.hp)/60)};if(!this.spend(cost)){this.notice('Not enough wood and stone to repair.');return;}this.assign(u,b,'repair');this.notice('Worker assigned to repairs.');}
 demolish(b){if(!b||b.type==='keep')return;for(const [r,n]of Object.entries(BUILDINGS[b.type].cost))this.resources[r]=Math.min(this.storage,this.resources[r]+Math.floor(n*(b.complete?.3:.8)));b.hp=0;this.clean();this.notice('Site cleared. Some resources recovered.');}
 command(point,stance='move'){const wall=this.world.buildingAt(this.buildings,Math.floor(point.x/TILE),Math.floor(point.y/TILE));if(wall&&['wall','palisade','gate'].includes(wall.type)&&this.units.some(u=>this.selected.includes(u.id)&&['archer','crossbow'].includes(u.type))){this.garrison(wall);return;}if(!this.world.walkable(this.world.at(point.x,point.y))){this.notice('Choose accessible land. Ground units cannot cross peaks or the sea.');return;}let i=0;for(const u of this.units.filter(u=>this.selected.includes(u.id))){if(u.garrison&&!this.dismount(u))continue;u.mountOrder=null;const target={x:clamp(point.x+(i%4)*16,20,this.world.cols*TILE-20),y:clamp(point.y+Math.floor(i/4)*16,20,this.world.rows*TILE-20)};if(!this.world.walkable(this.world.at(target.x,target.y)))Object.assign(target,point);const t=this.world.at(target.x,target.y);if(!this.world.reachable(u,this.buildings,this.revision).has(t.y*this.world.cols+t.x))continue;u.job=null;u.returnJob=null;u.target=target;u.path=[];u.pathRevision=-1;u.stance=stance;i++;}if(i){this.noteAction();this.effects.push({x:point.x,y:point.y,kind:'command',life:1,max:1});}else this.notice('No selected unit can reach that destination.');}
 move(u,target,dt,enemy=false){const flying=this.isAirborne(u);if(!flying&&!this.world.walkable(this.world.at(target.x,target.y)))return false;if(distance(u,target)<8)return true;const key=`${Math.floor(target.x/TILE)},${Math.floor(target.y/TILE)}`;
  if(!u.path?.length||u.pathRevision!==this.revision||u.pathGoal!==key){u.path=this.world.path(u,target,this.buildings,{enemy,flying,revision:this.revision});u.pathRevision=this.revision;u.pathGoal=key;}
  if(!u.path.length)return this.world.at(u.x,u.y)===this.world.at(target.x,target.y);
  const p=u.path[0],block=this.world.buildingAt(this.buildings,Math.floor(p.x/TILE),Math.floor(p.y/TILE));
  if(block&&block.type!=='road'&&(enemy||block.type!=='gate')&&!flying){if(enemy)this.hit(u,block,dt);else u.path=[];return false;}
  const d=enemy?ENEMIES[u.type]:UNITS[u.type],onRoad=this.world.buildingAt(this.buildings,Math.floor(u.x/TILE),Math.floor(u.y/TILE))?.type==='road';const len=distance(u,p),step=Math.min(len,d.speed*dt*(u.phase===2?1.8:1)*(u.rageUntil>this.time?1.4:1)*(u.auraBonus?1.1:1)*(onRoad?1.3:1)*(!enemy&&this.resources.food<=0?.65:1));const dx=(p.x-u.x)/Math.max(.001,len)*step,dy=(p.y-u.y)/Math.max(.001,len)*step;u.facing=Math.atan2(dy,dx);u.x+=dx;u.y+=dy;if(len<=step+.1)u.path.shift();return !u.path.length&&distance(u,target)<TILE*.5;
 }
 worker(u,dt){if(this.constructionWorker(u,dt))return;const job=u.job;if(!job){if(u.target&&this.move(u,u.target,dt))u.target=null;return;}const b=this.buildings.find(b=>b.id===job.building&&b.hp>0);if(!b){u.job=null;return;}
  if(job.kind==='build'||job.kind==='repair'){
   const goal=this.accessiblePoint(u,b);if(!goal||!this.move(u,goal,dt))return;
   if(job.kind==='build'){b.progress+=dt;if(b.progress>=BUILDINGS[b.type].time){b.complete=true;this.notice(`${BUILDINGS[b.type].name} completed.`);this.sound('build');for(const w of this.units.filter(w=>w.job?.building===b.id)){w.job=BUILDINGS[b.type].resource?{building:b.id,kind:'gather',stage:'travel',clock:0,carry:0}:null;}}}
   else{b.hp=Math.min(b.maxHp,b.hp+35*dt);if(b.hp>=b.maxHp)u.job=null;}return;
  }
  const resource=BUILDINGS[b.type].resource;
  if(job.stage==='return'){
   const points=this.buildings.filter(b=>b.complete&&(b.type==='keep'||b.type==='warehouse')).map(b=>this.accessiblePoint(u,b)).filter(Boolean).sort((a,b)=>distance(u,a)-distance(u,b));const point=points[0];if(!point){this.workerWarning(job,'No reachable storage. Open a route to the Keep or a Warehouse.');return;}
   if(this.move(u,point,dt)){const amount=Math.min(job.carry,Math.max(0,this.storage-this.resources[resource]));this.resources[resource]+=amount;this.stats.gathered+=amount;job.carry-=amount;if(job.carry<=0){job.stage='travel';job.warning=null;}else this.workerWarning(job,'Storage is full. Spend resources or build a Warehouse.');}return;
  }
  let tile=job.tile!=null?this.world.tiles[job.tile]:null;if(resource!=='food'&&(!tile||tile.resource!==resource||tile.amount<=0||job.navRevision!==this.revision)){
   tile=this.world.deposits(resource,b,u,this.buildings,this.revision)[0];if(!tile){if(job.carry>0){job.stage='return';return;}this.workerWarning(job,`No reachable ${resource} remains near ${BUILDINGS[b.type].name}.`);return;}job.tile=tile.y*this.world.cols+tile.x;job.navRevision=this.revision;job.warning=null;
  }
  const point=resource==='food'?this.accessiblePoint(u,b):{x:(tile.x+.5)*TILE,y:(tile.y+.5)*TILE};if(!point||!this.move(u,point,dt))return;job.clock+=dt;
  if(job.clock>=1.4){job.clock=0;if(resource!=='food')this.sound(resource==='wood'?'chop':'mine');const amount=Math.min(4*b.level*(1+this.researchBonus(resource)),resource==='food'?Infinity:tile.amount);job.carry+=amount;if(tile){tile.amount-=amount;if(tile.amount<=0){tile.resource=null;this.revision++;}}if(job.carry>=16*(1+this.researchBonus('carry'))){job.stage='return';u.path=[];}this.effects.push({x:u.x,y:u.y-8,kind:'gather',life:.4,max:.4});}
 }
 accessiblePoint(u,b){const reachable=this.world.reachable(u,this.buildings,this.revision);return this.world.accessPoints(b,this.buildings).filter(p=>reachable.has(Math.floor(p.y/TILE)*this.world.cols+Math.floor(p.x/TILE))).sort((a,c)=>distance(u,a)-distance(u,c))[0];}
 workerWarning(job,message){if(job.warning!==message){job.warning=message;this.notice(message);}}
 clean(){for(const e of this.enemies.filter(e=>e.hp<=0)){this.stats.kills++;this.resources.gold=Math.min(this.storage,this.resources.gold+(ENEMIES[e.type].boss?80:2));this.effects.push({x:e.x,y:e.y,kind:'death',life:.7,max:.7});if(e.type==='conqueror')this.breakSeal();if(e.type==='demonlord')this.demonLordDefeated=true;if(e.type==='dragon'){const land=this.world.tiles.filter(t=>this.world.walkable(t)&&!this.world.buildingAt(this.buildings,t.x,t.y)).sort((a,b)=>Math.hypot((a.x+.5)*TILE-e.x,(a.y+.5)*TILE-e.y)-Math.hypot((b.x+.5)*TILE-e.x,(b.y+.5)*TILE-e.y))[0];this.spawnEnemy('conqueror',land?(land.x+.5)*TILE:e.x,land?(land.y+.5)*TILE:e.y);this.notice('The dragon falls. The Conqueror rises!');this.sound('wave');}}
  const destroyed=this.buildings.filter(b=>b.hp<=0);if(destroyed.some(b=>b.type==='keep')){this.over=true;this.victory=false;this.notice('The Keep has fallen.');}
  if(destroyed.length){this.revision++;this.sound('collapse');}if(this.over&&!this.endSound){this.endSound=true;this.sound('defeat');}this.stats.lost+=this.units.filter(u=>u.hp<=0).length;this.buildings=this.buildings.filter(b=>b.hp>0);this.units=this.units.filter(u=>u.hp>0);this.enemies=this.enemies.filter(e=>e.hp>0);
 }
 update(dt){if(this.paused||this.over)return;dt=Math.min(dt,.1)*this.speed;this.time+=dt;this.updateProgression(dt);this.constructionClock=(this.constructionClock||0)-dt;if(this.constructionClock<=0){this.constructionClock=.5;this.scheduleConstruction();}this.resources.food=Math.max(0,this.resources.food-this.units.length*.015*dt*(this.hasActed?1:0));for(const u of this.units)if(u.type==='worker')this.worker(u,dt);
  this.updateShips(dt);this.updateNightmare(dt);this.fight(dt);this.clean();for(const fx of this.effects)fx.life-=dt;this.effects=this.effects.filter(fx=>fx.life>0).slice(-250);
  if(this.over)return;if(this.active&&!this.enemies.length&&!this.ships.some(s=>!s.landed)&&!this.portals.some(p=>p.queue.length)&&!this.hazards.length){this.active=false;this.timer=this.autoWave?5:(DIFFICULTIES[this.difficulty]||DIFFICULTIES.normal).interval;this.notice(`Wave ${this.wave} survived. Repair and prepare.`);if(this.wave>=this.campaignLength()&&!this.endless){this.over=true;this.victory=true;this.sound('victory');}this.autosave();}
  if(!this.active&&!this.preparationHeld){this.timer-=dt;if(this.timer<=0)this.startWave();}this.saveClock+=dt;if(this.saveClock>=30){this.saveClock=0;this.autosave();}
 }
 serialize(){return {version:1,seed:this.world.seed,cols:this.world.cols,rows:this.world.rows,island:this.world.island,kingdomName:this.kingdomName,keepDesign:this.keepDesign,tiles:this.world.tiles,resources:this.resources,buildings:this.buildings,units:this.units,enemies:this.enemies,ships:this.ships,id:this.id,wave:this.wave,timer:this.timer,active:this.active,time:this.time,tech:this.tech,researched:this.researched,researchTask:this.researchTask,stats:this.stats,over:this.over,victory:this.victory,endless:this.endless,autoWave:this.autoWave,hasActed:this.hasActed,tutorial:this.tutorial,portals:this.portals,hazards:this.hazards,sealBroken:this.sealBroken,sealTime:this.sealTime,demonLordDefeated:this.demonLordDefeated,difficulty:this.difficulty};}
 static restore(data){if(data?.version!==1||!Array.isArray(data.tiles)||data.tiles.length!==(data.cols||COLS)*(data.rows||ROWS)||!Array.isArray(data.buildings)||!Array.isArray(data.units)||!Array.isArray(data.enemies)||!Array.isArray(data.ships)||!data.resources)throw Error('Invalid save');for(const r of ['wood','stone','food','iron','gold'])if(!Number.isFinite(data.resources[r])||data.resources[r]<0)throw Error('Invalid resources');for(const b of data.buildings)if(!BUILDINGS[b.type]||!Number.isFinite(b.hp)||!Number.isFinite(b.x)||!Number.isFinite(b.y))throw Error('Invalid building');for(const u of data.units)if(!UNITS[u.type])throw Error('Invalid unit');for(const e of data.enemies)if(!ENEMIES[e.type])throw Error('Invalid enemy');const g=new Game(data.seed,data.difficulty,data.tiles,{cols:data.cols||COLS,rows:data.rows||ROWS,island:data.island||false,name:data.kingdomName,keepDesign:data.keepDesign});for(const key of ['resources','buildings','units','enemies','ships','id','wave','timer','active','time','tech','stats','over','victory','endless'])g[key]=data[key];g.portals=data.portals||[];g.hazards=data.hazards||[];g.sealBroken=data.sealBroken||false;g.sealTime=data.sealTime||0;g.demonLordDefeated=data.demonLordDefeated||false;g.autoWave=data.autoWave||false;g.hasActed=data.hasActed??true;g.tutorial=data.tutorial&&Number.isInteger(data.tutorial.step)?{step:Math.max(0,Math.min(5,data.tutorial.step)),done:!!data.tutorial.done}:null;g.researched=data.researched||[];g.researchTask=data.researchTask||null;g.world.tiles=data.tiles;return g;}
}

Object.assign(Game.prototype,Construction,Progression,Invasions,Garrison,Nightmare,Combat);
