import {BUILDINGS,UNITS,RESOURCES} from './data.js';
const $=id=>document.getElementById(id);
const costText=cost=>Object.entries(cost).map(([r,n])=>`${RESOURCES[r]} ${n}`).join(' · ');
export class UI {
 constructor(game,renderer,input,saves,audio,onGame){Object.assign(this,{game,renderer,input,saves,audio,onGame});this.tab='build';this.category='Economy';this.lastPanel='';this.toastUntil=0;this.modalPause=false;
  $('resources').innerHTML=Object.entries({...RESOURCES,pop:'♙'}).map(([r,s])=>`<div class="resource" title="${r==='pop'?'Population':r}"><span class="symbol">${s}</span><div><small>${r==='pop'?'People':r}</small><strong id="res-${r}">0</strong></div></div>`).join('');
  $('tabs').onclick=e=>{const tab=e.target.closest('[data-tab]');if(tab){this.tab=tab.dataset.tab;this.renderPanel(true);}};
  $('panel').onclick=e=>this.action(e);$('next-wave').onclick=()=>game.startWave();$('pause').onclick=()=>game.paused=!game.paused;$('speed').onclick=()=>game.speed=game.speed===1?2:1;
  $('zoom-in').onclick=()=>renderer.zoom(1.2);$('zoom-out').onclick=()=>renderer.zoom(1/1.2);$('home').onclick=()=>renderer.center();$('confirm-build').onclick=()=>input.place();$('cancel-build').onclick=()=>{renderer.preview=null;this.renderPanel(true);};$('menu').onclick=()=>this.menu();$('help').onclick=()=>this.help();document.querySelector('.brand').onclick=e=>{e.preventDefault();this.menu();};
  $('minimap').onpointerdown=e=>{const r=e.target.getBoundingClientRect();renderer.camera.x=(e.clientX-r.left)/r.width*2560;renderer.camera.y=(e.clientY-r.top)/r.height*1920;};
  $('modal').onclose=()=>{game.paused=this.modalPause;};$('modal').oncancel=()=>{};game.notice=message=>this.toast(message);game.sound=kind=>audio.play(kind);game.autosave=()=>{if(!saves.save(game)&&!this.saveWarning){this.saveWarning=true;this.toast('Browser storage is unavailable. Keep this tab open to retain progress.');}};this.renderPanel(true);
 }
 toast(message){$('toast').textContent=message;this.toastUntil=performance.now()+4000;$('toast').classList.add('visible');}
 selection(){if(this.game.selected.length)this.tab='inspect';this.renderPanel(true);}
 renderPanel(force=false){const g=this.game,b=g.buildings.find(b=>g.selected.includes(b.id)),units=g.units.filter(u=>g.selected.includes(u.id));const key=[this.tab,this.category,g.level,g.tech,b?.id,b?.complete,b?.level,g.units.filter(u=>u.job?.building===b?.id).length,units.map(u=>u.id).join(','),g.buildings.filter(b=>b.complete).map(b=>b.type).join(',')].join('|');if(key===this.lastPanel&&!force)return;this.lastPanel=key;
  for(const button of document.querySelectorAll('[data-tab]'))button.classList.toggle('active',button.dataset.tab===this.tab);
  if(this.tab==='build'){$('panel').innerHTML=`<div class="category">${['Economy','Town','Military','Defense'].map(name=>`<button data-category="${name}" class="${this.category===name?'active':''}">${name}</button>`).join('')}</div><p class="section-label">Lay the foundations</p><div class="build-list">${Object.entries(BUILDINGS).filter(([,d])=>d.category===this.category).map(([type,d])=>`<button class="build-card" data-build="${type}" ${g.level<(d.level||1)?'disabled':''}><span class="icon">${d.icon}</span><span class="copy"><strong>${d.name}</strong><small>${g.level<(d.level||1)?`Requires Keep level ${d.level}`:d.desc}</small><span class="cost">${costText(d.cost)}</span></span><span class="plus">+</span></button>`).join('')}</div>`;}
  else if(this.tab==='army'){$('panel').innerHTML=`<p class="section-label">Rally your defenders</p><div class="action-list" style="margin:0 0 12px"><button data-action="select-army">Select army</button><button data-action="select-workers">Select workers</button></div><div class="build-list">${Object.entries(UNITS).map(([type,d])=>`<button class="build-card" data-recruit="${type}" ${!g.buildings.some(b=>b.type===d.building&&b.complete)||g.level<(d.level||1)?'disabled':''}><span class="icon">${d.icon}</span><span class="copy"><strong>${d.name}</strong><small>${BUILDINGS[d.building].name}${d.level?` · Keep ${d.level}`:''}</small><span class="cost">${costText(d.cost)}</span></span></button>`).join('')}</div>`;}
  else if(b){const d=BUILDINGS[b.type],workers=g.units.filter(u=>u.job?.building===b.id).length;$('panel').innerHTML=`<span class="eyebrow">${b.complete?'LEVEL '+b.level:'UNDER CONSTRUCTION'}</span><h2 class="inspect-title">${d.name}</h2><div class="details"><span id="selected-hp"></span><progress id="selected-progress" max="1"></progress>${d.resource?`Workers: ${workers} / ${d.workers}<br>Produces ${d.resource}; workers carry it to storage.`:d.desc}</div><div class="action-list">${d.workers||!b.complete?'<button data-action="assign">Assign worker</button><button data-action="unassign">Remove worker</button>':''}${b.complete?'<button data-action="repair">Repair</button>':''}${b.complete&&b.level<5?'<button data-action="upgrade">Upgrade '+costText({wood:100*b.level,stone:100*b.level,gold:50*b.level})+'</button>':''}${b.type==='keep'?'<button data-recruit="worker">Train worker · ♨ 30</button>':''}${b.type==='smith'?'<button data-action="research">Research · '+costText({iron:40*(g.tech+1),gold:50*(g.tech+1)})+'</button>':''}${b.type!=='keep'?'<button data-action="demolish">'+(b.complete?'Demolish':'Cancel construction')+'</button>':''}</div>`;}
  else if(units.length){$('panel').innerHTML=`<span class="eyebrow">YOUR PEOPLE</span><h2 class="inspect-title">${units.length===1?UNITS[units[0].type].name:units.length+' units selected'}</h2><div class="details" id="unit-details"></div><div class="action-list"><button data-action="move">Move</button><button data-action="attack">Attack move</button><button data-action="hold">Hold position</button><button data-action="defend">Defend</button><button data-action="patrol">Patrol</button><button data-action="box">Box select</button><button data-action="idle">Release jobs</button></div>`;}
  else $('panel').innerHTML='<p class="empty">Select a building to assign workers, repair, or upgrade.<br><br>Select a unit to give orders. On touch, use <b>Move</b> then tap a destination. Find group selection in the Army tab.</p>';
 }
 action(e){const el=e.target.closest('button');if(!el)return;const g=this.game,b=g.buildings.find(b=>g.selected.includes(b.id));if(el.dataset.category){this.category=el.dataset.category;this.renderPanel(true);return;}if(el.dataset.build){this.input.begin(el.dataset.build);this.toast('Choose a site on the map. Touch: tap a site, then Place here.');return;}if(el.dataset.recruit){g.recruit(el.dataset.recruit);this.renderPanel(true);return;}
  switch(el.dataset.action){case'assign':g.assignWorker(b);break;case'unassign':g.removeWorker(b);break;case'repair':g.repair(b);break;case'upgrade':g.upgrade(b);break;case'research':g.research();break;case'demolish':this.dialog(`<span class="eyebrow">CLEAR THIS SITE</span><h2>Remove ${BUILDINGS[b.type].name}?</h2><p>${b.complete?'Recover 30% of the original construction cost.':'Cancel construction and recover 80% of the cost.'} Assigned workers will become idle.</p><div class="modal-actions"><button id="remove-site">Remove building</button><button data-close>Keep building</button></div>`);$('remove-site').onclick=()=>{g.demolish(b);$('modal').close();this.renderPanel(true);};break;
  case'select-army':g.selected=g.units.filter(u=>u.type!=='worker').map(u=>u.id);this.tab='inspect';break;case'select-workers':g.selected=g.units.filter(u=>u.type==='worker').map(u=>u.id);this.tab='inspect';break;
  case'move':case'attack':case'patrol':this.input.commandMode=el.dataset.action;this.toast('Tap or click a destination on the map.');break;case'box':this.input.mode='box';this.toast('Drag a box around your units.');break;case'hold':case'defend':case'idle':for(const u of g.units.filter(u=>g.selected.includes(u.id))){u.stance=el.dataset.action==='hold'?'hold':'defend';u.target=null;u.path=[];if(el.dataset.action==='idle')u.job=null;}this.toast('Orders updated.');break;
  }this.renderPanel(true);
 }
 update(){const g=this.game;for(const r in RESOURCES)$('res-'+r).textContent=Math.floor(g.resources[r]);$('res-pop').textContent=`${g.units.length}/${g.capacity}`;$('wave').textContent=g.wave?`Wave ${g.wave}${g.endless?'':' / 50'}`:'A new kingdom';$('timer').textContent=g.active?`${g.enemies.length} foes`:`${String(Math.floor(g.timer/60)).padStart(2,'0')}:${String(Math.floor(g.timer%60)).padStart(2,'0')}`;$('wave-state').textContent=g.active?'Defend the Keep. Hold the coast.':g.wave?'The coast holds. Prepare for the next tide.':'The sea is quiet. For now.';$('next-wave').disabled=g.active||g.over;$('pause').textContent=g.paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',g.paused?'Resume game':'Pause game');$('speed').textContent=g.speed+'×';$('status').textContent=`${g.units.filter(u=>u.type==='worker'&&!u.job).length} idle workers · ${g.stats.kills} enemies defeated`;$('hint').textContent=this.input.touch?'Drag to explore · Pinch to zoom · Tap to select':'WASD to explore · Scroll to zoom · Right-click to move';document.querySelector('.seal').textContent=['I','II','III','IV','V'][g.level-1];
  const p=this.renderer.preview;$('placement').hidden=!p;if(p){$('placement-label').textContent=BUILDINGS[p.type].name;$('confirm-build').disabled=!g.world.valid(p.type,p.tx,p.ty,g.buildings)||!g.afford(BUILDINGS[p.type].cost);}
  if(performance.now()>this.toastUntil)$('toast').classList.remove('visible');this.renderPanel();const b=g.buildings.find(b=>g.selected.includes(b.id));if(b&&$('selected-hp')){$('selected-hp').textContent=`HP ${Math.ceil(b.hp)} / ${b.maxHp}`;$('selected-progress').value=b.complete?b.hp/b.maxHp:b.progress/Math.max(1,BUILDINGS[b.type].time);}
  if($('unit-details')){const units=g.units.filter(u=>g.selected.includes(u.id));$('unit-details').textContent=units.length===1?`HP ${Math.ceil(units[0].hp)} / ${units[0].maxHp} · ${UNITS[units[0].type].damage} damage · ${units[0].kills} kills · ${units[0].job?.kind||units[0].stance}`:'Use orders below, then choose a destination.';}
  const boss=g.enemies.find(e=>e.type in {captain:1,chief:1,brute:1,champion:1,giant:1,titan:1,blackknight:1,warlord:1,dragonknight:1,dragon:1,conqueror:1});$('boss').hidden=!boss;if(boss){const names={captain:'Raider Captain',chief:'Barbarian Chief',brute:'Ogre Brute',champion:'Ogre Champion',giant:'Stone Giant',titan:'The Titan',blackknight:'Black Knight',warlord:'The Warlord',dragonknight:'Dragon Knight',dragon:'Black Dragon · Phase I',conqueror:'The Conqueror · Phase II'};$('boss').innerHTML=`${names[boss.type]}<progress max="${boss.maxHp}" value="${boss.hp}"></progress>`;}
  if(g.over&&!this.endShown){this.endShown=true;this.ending();}
 }
 dialog(html){const modal=$('modal');if(!modal.open){this.modalPause=this.game.paused;this.game.paused=true;}$('modal-body').innerHTML=html;if(!modal.open)modal.showModal();for(const button of modal.querySelectorAll('[data-close]'))button.onclick=()=>modal.close();}
 welcome(){this.dialog(`<span class="eyebrow">A KINGDOM BEGINS WITH YOU</span><h2>Hold the coast.<br>Build your legacy.</h2><p>A lonely Keep. Five workers. A sea full of enemies.<br>Raise a kingdom from nothing, and withstand fifty invasions.</p><label class="section-label" for="difficulty">Choose your challenge</label><select id="difficulty"><option value="normal">Normal · The intended challenge</option><option value="easy">Easy · A gentler beginning</option><option value="hard">Hard · A relentless coast</option></select><div class="modal-actions"><button id="new-game" class="primary">Found a kingdom →</button>${this.saves.has()?'<button id="continue">Continue kingdom</button>':''}<button id="welcome-help">How to play</button></div>`);$('new-game').onclick=()=>{const difficulty=$('difficulty').value;$('modal').close();this.onGame(null,difficulty);};if($('continue'))$('continue').onclick=()=>this.load();$('welcome-help').onclick=()=>this.help(true);}
 load(){try{const g=this.saves.load();if(!g)throw Error('No save');$('modal').close();this.onGame(g);}catch{this.toast('This save could not be loaded. Start a new kingdom to play.');}}
 menu(){this.dialog(`<span class="eyebrow">TIDEHOLD</span><h2>A moment of calm.</h2><p>Your kingdom is paused while this menu is open.</p><div class="modal-actions"><button class="primary" data-close>Return to kingdom</button><button id="save">Save kingdom</button><button id="load" ${this.saves.has()?'':'disabled'}>Load saved game</button><button id="sound">Sound: ${this.audio.enabled?'on':'off'}</button><button id="instructions">How to play</button><button id="restart">New kingdom</button></div>`);$('save').onclick=()=>this.toast(this.saves.save(this.game)?'Kingdom saved on this browser.':'Browser storage is unavailable.');$('load').onclick=()=>this.load();$('sound').onclick=()=>{this.audio.enabled=!this.audio.enabled;$('sound').textContent='Sound: '+(this.audio.enabled?'on':'off');this.audio.play('build');try{this.saves.storage.setItem('tidehold.sound',String(this.audio.enabled));}catch{}};$('instructions').onclick=()=>this.help();$('restart').onclick=()=>{this.dialog('<span class="eyebrow">A FRESH START</span><h2>Found another kingdom?</h2><p>The current kingdom will be replaced. Save first if you want to keep a copy in this browser.</p><div class="modal-actions"><button id="confirm-new">Start fresh</button><button data-close>Keep playing</button></div>');$('confirm-new').onclick=()=>this.welcome();};}
 help(welcome=false){this.dialog(`<span class="eyebrow">THE FIELD GUIDE</span><h2>Your first foothold.</h2><p>Build a <b>Lumber Camp</b> near trees and a <b>Farm</b>. Two idle workers help construct each site, then keep working there. Select buildings to assign or release workers. Build houses, train workers at the Keep, and establish a Quarry.</p><p>Build a Barracks or Archery Range to recruit defenders. Protect the Keep with towers and walls; leave gates for your people. Upgrade your Keep to unlock advanced buildings. Enemy ships arrive when the preparation timer runs out.</p><div class="help-grid"><div><strong>Mouse & keyboard</strong>WASD / arrows: camera<br>Wheel: zoom<br>Left click: select / build<br>Left drag: group selection<br>Shift: add to selection<br>Right click: move<br>Right / middle drag: pan<br>Space: pause · Esc: cancel</div><div><strong>Touch</strong>One-finger drag: pan<br>Pinch: zoom<br>Tap: select / preview<br>Place here: confirm building<br>Army: select your troops<br>Move, then tap: give orders<br>Box select: drag a selection<br>Two fingers: pan and zoom</div></div><p>Pause to plan. Saves stay in this browser; autosave runs every 30 game seconds and after waves. The Keep falling ends the run.</p><div class="modal-actions"><button id="help-back" class="primary">${welcome?'Choose your kingdom':'Return to kingdom'}</button></div>`);$('help-back').onclick=()=>welcome?this.welcome():$('modal').close();}
 ending(){const g=this.game;this.dialog(`<span class="eyebrow">${g.victory?'THE KINGDOM HAS SURVIVED':'THE LAST BANNER FALLS'}</span><h2>${g.victory?'The coast is yours.':'A kingdom remembered.'}</h2><p>Waves reached: ${g.wave} · Enemies defeated: ${g.stats.kills}<br>Structures built: ${g.stats.built} · People lost: ${g.stats.lost}<br>Score: ${g.stats.kills*10+g.wave*100+g.stats.built*20}</p><div class="modal-actions">${g.victory?'<button id="endless" class="primary">Enter endless mode</button>':''}<button id="again">Found a new kingdom</button><button data-close>View kingdom</button></div>`);$('again').onclick=()=>this.welcome();if($('endless'))$('endless').onclick=()=>{g.endless=true;g.over=false;g.victory=false;g.timer=120;this.endShown=false;$('modal').close();g.autosave();};}
}
